#!/usr/bin/env sh
_=0// "exec" "/usr/bin/env" "node" "--no-warnings" "$0" "$@"
 

const noi = require("./noi.js");
const cmd = process.argv[2];

if (cmd) {
  noi.cli(cmd, process.argv.slice(3));
} else {
  noi.repl();
}
